# -*- coding: utf-8 -*-
"""Atividade.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12JtXRdto0RnZKpkx5Hx4p0ZGMK7Pf1Zw
"""

from PIL import Image
import matplotlib.pyplot as plt
import numpy as np

# Carregar imagens
circle_img = Image.open('/content/circle.jpg')
line_img = Image.open('/content/line.jpg')

# Converter para RGB
circle_img = circle_img.convert('RGBA')
line_img = line_img.convert('RGBA')

# Remova o fundo branco e torne as imagens transparentes
circle_img_array = np.array(circle_img)
circle_img_array[(circle_img_array[:, :, 0] > 245) & (circle_img_array[:, :, 1] > 245) & (circle_img_array[:, :, 2] > 245), 3] = 0
circle_img = Image.fromarray(circle_img_array)

line_img_array = np.array(line_img)
line_img_array[(line_img_array[:, :, 0] > 245) & (line_img_array[:, :, 1] > 245) & (line_img_array[:, :, 2] > 245), 3] = 0
line_img = Image.fromarray(line_img_array)

# head
head = circle_img

# tronco
torso = line_img.rotate(90)  # Rotate the torso 90 degrees

# braços
arm_width, arm_height = int(torso.width * 0.75), int(torso.height * 0.75)
arm_img = line_img.resize((arm_width, arm_height))
arm1 = arm_img
arm2 = arm_img

# pernas
leg_width, leg_height = int(arm_width * 2), int(arm_height * 2)
leg_img = line_img.resize((leg_width, leg_height))
leg1 = leg_img
leg2 = leg_img.rotate(90)

# Boneco
stick_figure = Image.new('RGBA', (300, 300), (0, 0, 0, 0))  # Create a transparent background
stick_figure.paste(head, (100, 25), head)  # Position the head
stick_figure.paste(torso, (100, 75), torso)  # Position the torso
stick_figure.paste(arm1, (80, 75), arm1)  # Position the left arm
stick_figure.paste(arm2, (140, 75), arm2)  # Position the right arm
stick_figure.paste(leg1, (135, 95), leg1)  # Position the left leg
stick_figure.paste(leg2, (69, 152), leg2)  # Position the right leg

# Imagem Final
plt.imshow(stick_figure)
plt.show()

