# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lGyjLfGWXfAOOxuzImNSAohg0Fb35uNu
"""

import sys
import cv2
import numpy as np
import matplotlib.pyplot as plt

#abre imagen
filename = "/content/gamora_nebula.jpg"
im = cv2.imread(filename)

#redimensiona a imagem
new_width = int(im.shape[1] * .5)
new_height = int(im.shape[0] * .5)
dim = (new_width, new_height)
im_resized = cv2.resize(im, dim, interpolation = cv2.INTER_AREA)

im = cv2.cvtColor(im_resized, cv2.COLOR_BGR2HSV)
i = cv2.cvtColor(im_resized, cv2.COLOR_BGR2RGB)
r, g, b = cv2.split(im)
im1 = r
im2 = g
im3 = b
y1 = 100
x1 = 50
y2 = 225
x2 = 350
green = im1[y1,x1]
blue = im1[y2,x2]
mask_person1 = cv2.inRange(im1, np.array(green), np.array(im1[250,150]))



ret, mask_person2 = cv2.threshold(im1, 58, 255, cv2.THRESH_BINARY)
inverted_mask = cv2.bitwise_not(mask_person2)
imresul = cv2.cvtColor(im, cv2.COLOR_HSV2RGB)
verde = im[300,500]
azul = im[50,120]
imresul[mask_person1>0] = azul
imresul[inverted_mask>0] = verde
plt.imshow(mask_person1)
plt.show()
plt.imshow(im1)
plt.show()
plt.imshow(imresul)
plt.show()