# -*- coding: utf-8 -*-
"""Questão 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rgcclx0pp6pTFwvSDu-Csvb2AekzsztM
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt

# Carregar a imagem
img = cv2.imread('/content/shaco.jpeg')

# Verificar se a imagem foi carregada corretamente
if img is None:
    print("Erro ao carregar a imagem.")
    exit()

# Criar uma imagem da cor sépia fixa (108, 84, 19)
sepia_color = np.array([19, 84, 108], dtype=np.uint8)  # Cor BGR

# Aplicar uma mistura da imagem original com o filtro sépia
sepia_img = cv2.addWeighted(img, 0.6, np.full_like(img, sepia_color), 0.4, 0)

# Exibir as imagens lado a lado
fig, ax = plt.subplots(1, 2, figsize=(10, 5))

ax[0].imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
ax[0].set_title('Imagem Original')

ax[1].imshow(cv2.cvtColor(sepia_img, cv2.COLOR_BGR2RGB))
ax[1].set_title('Imagem em Sépia Fixa')

plt.show()

