# -*- coding: utf-8 -*-
"""Questão 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j5PjRv1FCT17HwOXfdGzEkUpWxODc2b7
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt

# Carregar a imagem
img = cv2.imread('/content/shaco.jpeg')

# Verificar se a imagem foi carregada corretamente
if img is None:
    print("Erro ao carregar a imagem.")
    exit()

# Converter para escala de cinza, independentemente do tipo de dado
R, G, B = cv2.split(img)
Y = (0.3 * R) + (0.59 * G) + (0.11 * B)

# Converter o resultado para 8 bits, se necessário
if img.dtype != np.uint8:
    Y = cv2.convertScaleAbs(Y)

# Converter de volta para 3 canais
gray_img = cv2.cvtColor(Y.astype(np.uint8), cv2.COLOR_GRAY2BGR)

# Exibir as imagens lado a lado
fig, ax = plt.subplots(1, 2, figsize=(10, 5))

ax[0].imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
ax[0].set_title('Imagem Original')

ax[1].imshow(cv2.cvtColor(gray_img, cv2.COLOR_BGR2RGB))
ax[1].set_title('Imagem em Tons de Cinza')

plt.show()

